### ISSUE TITLE
Workspace build for CMCC 2301.1 failed using latest image

### ISSUE THREAD

**Issue by dascheib** [provocon/coremedia-build-docker#3]
Hi!

We tried to build the coremedia workspace of version 2301.1 with the latest image (package 2007) via gitlab pipeline. The maven build failed first with the following message: 

    Failed to instantiate [com.coremedia.transform.image.java2d.Java2DImageInputAdapter]:
    Factory method 'imageTransformerInputAdapter' threw exception; nested exception is java.lang.UnsatisfiedLinkError:
    /usr/local/zulu11.60.19-ca-jdk11.0.17-linux_musl_x64/lib/libawt_xawt.so:
    Error loading shared library libXext.so.6:
    No such file or directory (needed by /usr/local/zulu11.60.19-ca-jdk11.0.17-linux_musl_x64/lib/libawt_xawt.so)

We later had success by installing the missing libraries after installing the image:

    apk add libxext
    apk add libxrender
    apk add libxtst
    apk add libxi

We'd appriciate, if you could extend the image to include the missing libraries.

Thank you in advance!
Daniel

**Comment by mgoellnitz** [comment]
Hi @dascheib ,
thanks for pointing this out. Two questions, just to be sure:
1. Did this occur with 2301 first? We can't see this dependency problem in our 22xy-build-logs.
2. We're talking of 2207 not 2007, right?

**Comment by dascheib** [comment]
Hi @mgoellnitz 
we upgraded from 2204.1 to 2301.1, so we had to switch the image from 2110.3 to 2207, so we would be able to use pnpm@7 for frontend and studio build. We never had this problem so far, but we skipped a few versions and this is the first time we used the 2207 image. And yes, it's the 2207, because it should be the only one with pnpm@7.

Edit:
I just realized, I typed 2007 instead of 2207 in the first message. I'm sorry for the confusion.

**Comment by mgoellnitz** [comment]
Hi @dascheib 
we seem to have a bit of a tag screw up, since 2207 is newer than 2207.2 which were supposed to be exactly the same package. We'll have to discuss that with the build pipeline (gitlab or github side - which describes the problem.).
But, I cannot confirm that we cannot build with maven or receive messages for missing dependencies.
Before preparing an updated image, I would like to confirm the problem and double check with a new image.
I'm using (nearly) the example build file. Anything on your side you could share, that's different on your side?

**Comment by dascheib** [comment]
Hi @mgoellnitz,
The workspace to build is a project customizing the CoreMedia 11 workspace. Because the issue during the build occured with a bean called **Java2DImageInputAdapter**, located in the _com.coremedia.cms:coremedia-transform_ module, which is not used and/or modified by project code (neither is the configuration in module _com.coremedia.blueprint:blueprint-spring-boot-autoconfigure_), I assumed, it would be a general and no project specific issue. 
I will try to reproduce the issue with a plain version of CoreMedia, but I'm not sure, yet, if we have a corresponding branch or project. Also I cannot tell anything more about the used image, as it is stored in an internal artifactory and I was told to open an issue about it here. I'm rechecking, if there is a colleague with a more firm devops background.

**Comment by mgoellnitz** [comment]
So,
new images tested following the example CI-files with the 2303 branch. @dascheib Could you please give them a try and provide feedback, if the added dependencies did the trick on your side.

**Comment by dascheib** [comment]
Hi @mgoellnitz,
is this somehow related to version [2207.3](https://github.com/provocon/coremedia-build-docker/releases/tag/2207.3) of the Image? If yes - did you raise the version of Alpine Linux to 3.17? If yes, this seems to have the sideffect of raising the versions of Node.js (18.14.2) and npm (9.1.2) to unsupported versions. CoreMedia only supports version 16.X of Node.js (LTS).

**Comment by mgoellnitz** [comment]
Hi @dascheib ,
yes, only 16.x is supported and the intended version of the image. The version of alpine is used from the underlying docker images. Question remains, why our tests don't show those problems, and builds don't fail. Thanks.

**Comment by mgoellnitz** [comment]
Hi @dascheib ,
fixed tag 2207.3 (base version remains the same, to indicate the minimum CMCC version for this image) is available via docker hub.

**Comment by dascheib** [comment]
Hi @mgoellnitz,
that completely fixed our build. 
Thank you very much!
Daniel
